# Generated by Django 5.1.7 on 2026-08-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField()),
                ('n_customers', models.IntegerField()),
                ('months', models.IntegerField()),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservableEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=32)),
                ('timestamp', models.DateField()),
                ('amount', models.FloatField()),
                ('reason_code', models.CharField(max_length=32)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simulator.simulationrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'reason_code'], name='simulator_o_run_id_116384_idx'), models.Index(fields=['run', 'customer_id'], name='simulator_o_run_id_244b75_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyntheticCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=32)),
                ('bank', models.CharField(max_length=32)),
                ('subscription_amount', models.FloatField()),
                ('due_day', models.IntegerField()),
                ('starting_balance', models.FloatField()),
                ('salary_day', models.IntegerField()),
                ('salary_amount', models.FloatField()),
                ('daily_burn', models.FloatField()),
                ('card_valid_until', models.DateField(blank=True, null=True)),
                ('mandate_revoked_on', models.DateField(blank=True, null=True)),
                ('account_closed_on', models.DateField(blank=True, null=True)),
                ('base_network_error_rate', models.FloatField(default=0.03)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='simulator.simulationrun')),
            ],
            options={
                'unique_together': {('run', 'customer_id')},
            },
        ),
    ]
