# Generated by Django 5.1.7 on 2026-08-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observableevent',
            name='raw_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='EventGroundTruth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_reason_code', models.CharField(max_length=32)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ground_truth', to='simulator.observableevent')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_truths', to='simulator.simulationrun')),
            ],
        ),
    ]
