# Generated by Django 5.1.7 on 2026-08-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_observableevent_raw_text_eventgroundtruth'),
    ]

    operations = [
        migrations.AddField(
            model_name='observableevent',
            name='bank',
            field=models.CharField(default='UNKNOWN', max_length=32),
        ),
    ]
