# Generated by Django 5.1.7 on 2026-08-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seed', models.IntegerField()),
                ('n_customers', models.IntegerField(default=200)),
                ('months', models.IntegerField(default=4)),
                ('total_failures', models.IntegerField()),
                ('hard_declines_skipped', models.IntegerField(default=0)),
                ('policy_attempts', models.IntegerField()),
                ('policy_successes', models.IntegerField()),
                ('policy_rupees_recovered', models.DecimalField(decimal_places=2, max_digits=14)),
                ('policy_retry_cost_spent', models.DecimalField(decimal_places=2, max_digits=14)),
                ('naive_attempts', models.IntegerField()),
                ('naive_successes', models.IntegerField()),
                ('naive_rupees_recovered', models.DecimalField(decimal_places=2, max_digits=14)),
                ('naive_retry_cost_spent', models.DecimalField(decimal_places=2, max_digits=14)),
                ('useless_retries_avoided_pct', models.FloatField(default=0.0)),
                ('notes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
