# Generated by Django 5.1.7 on 2026-08-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('event_timestamp', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('classification', 'Classification'), ('ev_gate', 'EV Gate'), ('retry_timing', 'Retry Timing'), ('bank_pattern', 'Bank Pattern Adjustment'), ('backtest', 'Backtest Run')], db_index=True, max_length=32)),
                ('bucket', models.CharField(blank=True, default='', max_length=16)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('decision_summary', models.CharField(max_length=255)),
                ('reasoning', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id', 'created_at'], name='audit_audit_custome_51aec9_idx'), models.Index(fields=['stage', 'created_at'], name='audit_audit_stage_df299a_idx')],
            },
        ),
    ]
